{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.6.0.jar",
          "url": "room-compiler-2.6.0.jar",
          "size": 5316003,
          "sha512": "578458298cac7b0ea4ad26b2ab3fb9a90e1e6ade27c2bd2ce5824427d91d45fcd2d1e1e6d22111725e622d9a25449b14495156c5475f34c22671ebe63a5c0577",
          "sha256": "f34c2d5c60d97b99f8e493e47a16cba4c36e27f16802f92d5dca005b44f87829",
          "sha1": "97ebde419ec41767251cf940d3babb934ddb5105",
          "md5": "9837ec55edb2c68659228ddf5bd61b2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.0-1.0.13"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-javapoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.41.2.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.6.0.jar",
          "url": "room-compiler-2.6.0.jar",
          "size": 5316003,
          "sha512": "578458298cac7b0ea4ad26b2ab3fb9a90e1e6ade27c2bd2ce5824427d91d45fcd2d1e1e6d22111725e622d9a25449b14495156c5475f34c22671ebe63a5c0577",
          "sha256": "f34c2d5c60d97b99f8e493e47a16cba4c36e27f16802f92d5dca005b44f87829",
          "sha1": "97ebde419ec41767251cf940d3babb934ddb5105",
          "md5": "9837ec55edb2c68659228ddf5bd61b2f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.6.0.jar",
          "url": "room-compiler-2.6.0.jar",
          "size": 5316003,
          "sha512": "578458298cac7b0ea4ad26b2ab3fb9a90e1e6ade27c2bd2ce5824427d91d45fcd2d1e1e6d22111725e622d9a25449b14495156c5475f34c22671ebe63a5c0577",
          "sha256": "f34c2d5c60d97b99f8e493e47a16cba4c36e27f16802f92d5dca005b44f87829",
          "sha1": "97ebde419ec41767251cf940d3babb934ddb5105",
          "md5": "9837ec55edb2c68659228ddf5bd61b2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-compiler is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-2.6.0-sources.jar",
          "url": "room-compiler-2.6.0-sources.jar",
          "size": 494324,
          "sha512": "3dc9a730b568c55a6182e3ce44926d200750617c020957068aa094cd732159e1190be03c805f4a6e2f0f1b0523e19070d126558a1f178c15ee2c68bc04e25ec2",
          "sha256": "b01fbec2c89851a3c404ba10bf688fd0e756a6c480d4da48baee8c45921c13d7",
          "sha1": "ee5e988be0111363de6678a2547910401cb43608",
          "md5": "a3eaafd56e7eb87f9df91785494d69e5"
        }
      ]
    }
  ]
}