{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.5.4-multiplatform-sources.jar",
          "url": "material-icons-core-1.5.4-multiplatform-sources.jar",
          "size": 481609,
          "sha512": "4b78c47576dcbae47efc0de2fb730e103f00e99e679b6342e29baeb7e19c0a5d5af2f5974ece05b432e1b5b1122a23e9263eb2d22e5fefb68fed5bdd8a33ae2f",
          "sha256": "9b786d9b9538a8bcb930d4e766d27ce6801c02ad38f62abe92277e815c83474f",
          "sha1": "ba5ec27f210b4d513b87002e6a40778f1f48219f",
          "md5": "135a10769d58bb5197fe779b1c08f821"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-metadata-1.5.4.jar",
          "url": "material-icons-core-1.5.4.jar",
          "size": 678,
          "sha512": "fd3290aaebad2f50d08a038350737f3adeaacba62b285c608be77a1c2ad2efeb4e87c41e688d1a3f597d1ae504031b188ffc6138116bdc7f4ad2866967952ce4",
          "sha256": "f8cbd92d3585570dce2541aefef0d59b4c591ae225d98921058e484e9abf3e42",
          "sha1": "ee649cf03c203f04b603fc3c0b832e4b31ffa64c",
          "md5": "de77e8efabe8be8213e75e431eaa5743"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-kotlin-1.5.4-sources.jar",
          "url": "material-icons-core-1.5.4-sources.jar",
          "size": 245508,
          "sha512": "14905fd8a0a3e679a92cf0650d82ada3294b49fe27ac7d1a607b0587244b381f4c591f63f5df5c4466a879eada76ee55b1dd2fc1eddc0a41640d6340fdb1a57f",
          "sha256": "48729ddeaa4270ce03e67a8a017ac6af4fb7ec988496ec87d1a5f9c5957aad4a",
          "sha1": "0e8bea2a68a490251b0c0c672cbf16bbcac861dc",
          "md5": "2dfcae2b1db00005e5e62eefdc988de1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-icons-core-android/1.5.4/material-icons-core-android-1.5.4.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-android",
        "version": "1.5.4"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-icons-core-android/1.5.4/material-icons-core-android-1.5.4.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-android",
        "version": "1.5.4"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-icons-core-android/1.5.4/material-icons-core-android-1.5.4.module",
        "group": "androidx.compose.material",
        "module": "material-icons-core-android",
        "version": "1.5.4"
      }
    }
  ]
}