{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-core/1.5.4/material-icons-core-1.5.4.module",
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-release.aar",
          "url": "material-icons-core-android-1.5.4.aar",
          "size": 717610,
          "sha512": "bdd9dad575664b6819b0e4720d330454191a5191b92346a148a3401d59336dc43deaf11d269f7dc3953a5fb33bb28a38ba40eabf19a49b62ba192de7a7b152d4",
          "sha256": "fc2bc75dcd539599a773e3a86dbb3a9899fdc58b65e919751f4a2d77bebbd187",
          "sha1": "57e3783c6f751c38a674d7ffb78538ccbb57c2d4",
          "md5": "2b498a30bdee924be2a87e1b1a638dcb"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.4"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-release.aar",
          "url": "material-icons-core-android-1.5.4.aar",
          "size": 717610,
          "sha512": "bdd9dad575664b6819b0e4720d330454191a5191b92346a148a3401d59336dc43deaf11d269f7dc3953a5fb33bb28a38ba40eabf19a49b62ba192de7a7b152d4",
          "sha256": "fc2bc75dcd539599a773e3a86dbb3a9899fdc58b65e919751f4a2d77bebbd187",
          "sha1": "57e3783c6f751c38a674d7ffb78538ccbb57c2d4",
          "md5": "2b498a30bdee924be2a87e1b1a638dcb"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-android-1.5.4-sources.jar",
          "url": "material-icons-core-android-1.5.4-sources.jar",
          "size": 245508,
          "sha512": "14905fd8a0a3e679a92cf0650d82ada3294b49fe27ac7d1a607b0587244b381f4c591f63f5df5c4466a879eada76ee55b1dd2fc1eddc0a41640d6340fdb1a57f",
          "sha256": "48729ddeaa4270ce03e67a8a017ac6af4fb7ec988496ec87d1a5f9c5957aad4a",
          "sha1": "0e8bea2a68a490251b0c0c672cbf16bbcac861dc",
          "md5": "2dfcae2b1db00005e5e62eefdc988de1"
        }
      ]
    }
  ]
}