{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-ktx",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.6.0.aar",
          "url": "room-ktx-2.6.0.aar",
          "size": 39257,
          "sha512": "5bae510a303ce5d6a51b01e40c8ce50606669aa89db4b6faede38124e4058af3610fde803a7632aa91c230d04f98c314903abd0044713b0887bb3b41b60c89bc",
          "sha256": "cd8bd8b2f4756f602c150b3ad4c1c9fae30818fb5cac6c245cfd7a1232de211d",
          "sha1": "89f1bf13d3ca7c5441726cfd61cdaaf0946e25ff",
          "md5": "b494a6861ed6e401fff763859e2d9c4a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.6.0.aar",
          "url": "room-ktx-2.6.0.aar",
          "size": 39257,
          "sha512": "5bae510a303ce5d6a51b01e40c8ce50606669aa89db4b6faede38124e4058af3610fde803a7632aa91c230d04f98c314903abd0044713b0887bb3b41b60c89bc",
          "sha256": "cd8bd8b2f4756f602c150b3ad4c1c9fae30818fb5cac6c245cfd7a1232de211d",
          "sha1": "89f1bf13d3ca7c5441726cfd61cdaaf0946e25ff",
          "md5": "b494a6861ed6e401fff763859e2d9c4a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.6.0-sources.jar",
          "url": "room-ktx-2.6.0-sources.jar",
          "size": 6915,
          "sha512": "89be0dc376b1e2c2108ce8ce07f099aa6a77fadeb7c3492497e7ca4978305eee701c0aa05540e981c8930d784482cb8cab28f0dcbda6fb54c310c5afd026f140",
          "sha256": "3118f596d5c3e70a2f8934db3d9655a71753f8d313dff794ab6b3ee1bf967547",
          "sha1": "dde5739324784ec695041f2c447905111a8adbe6",
          "md5": "7c6168fcf0542c0f8840f453ee7b9498"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.6.0"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.6.0-versionMetadata.json",
          "url": "room-ktx-2.6.0-versionMetadata.json",
          "size": 814,
          "sha512": "1c94a33cd9b1fbf050412e6cb6ea9da9a8502b88a79f92a5c3e34a48abab58b8b2cb7629609339e4f6507d21f82adcc68e78db6069c605f931f9d289b2e38405",
          "sha256": "354f00f9f639395f1b3b7b67f1b347930877a53d5478ee774a0fe2d0bff0e4a5",
          "sha1": "f30bf3b8e6bbd1c7e2f14f55088451a93592b71b",
          "md5": "6c27c68f0c9e5a610e3f76c99bb34c56"
        }
      ]
    }
  ]
}